apiVersion: v1
kind: PersistentVolume
metadata:
  name: metaphotor-settings
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 1Ki
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/custom.json