apiVersion: v1
kind: PersistentVolume
metadata:
  name: uwsgi-sock
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/uwsgi.sock