apiVersion: v1
kind: PersistentVolume
metadata:
  name: metaphotor-persist
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 2Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/persist