apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: metaphotor
data:
  nginx.conf: |
    worker_processes 1;
    events {
        worker_connections 1024;
    }
    http {
      sendfile on;
      client_max_body_size 1024M;
      keepalive_timeout 0;
      upstream app {
         server unix:/tmp/uwsgi.sock;
      }
      server {
        listen 80;
        listen [::]:80;
        server_name nginx.metaphotor;
        location / {
          try_files $uri @web;
          proxy_set_header Host $host;
          proxy_pass       http://127.0.0.1:31457/;
        }
        location @web {
          include uwsgi_params;
            uwsgi_pass app;
        }
      }
    }

  uwsgi_params: |
    uwsgi_param QUERY_STRING $query_string;
    uwsgi_param REQUEST_METHOD $request_method;
    uwsgi_param CONTENT_TYPE $content_type;
    uwsgi_param CONTENT_LENGTH $content_length;
    uwsgi_param REQUEST_URI $request_uri;
    uwsgi_param PATH_INFO $document_uri;
    uwsgi_param DOCUMENT_ROOT $document_root;
    uwsgi_param SERVER_PROTOCOL $server_protocol;
    uwsgi_param REMOTE_ADDR $remote_addr;
    uwsgi_param REMOTE_PORT $remote_port;
    uwsgi_param SERVER_ADDR $server_addr;
    uwsgi_param SERVER_PORT $server_port;
    uwsgi_param SERVER_NAME $server_name;
